export const userError = {
    INVALID_USERNAME_FORMAT: "INVALID_USERNAME_FORMAT",
    INVALID_EMAIL_FORMAT: "INVALID_EMAIL_FORMAT",
    INVALID_PASSWORD_FORMAT: "INVALID_PASSWORD_FORMAT",
    USER_NOT_FOUND: "USER_NOT_FOUND"
}

export const commonErrors = {
    DATABASE_UNAVAILABLE: "DATABASE_UNAVAILABLE",
}