export const userError = {
    INVALID_USERNAME_FORMAT: "INVALID_USERNAME_FORMAT",
    INVALID_EMAIL_FORMAT: "INVALID_EMAIL_FORMAT",
    INVALID_PASSWORD_FORMAT: "INVALID_PASSWORD_FORMAT",
    USER_NOT_FOUND: "USER_NOT_FOUND",
    FAILED_TO_RETRIEVE_USER: "FAILED_TO_RETRIEVE_USER",
    FAILED_TO_CREATE_USER: "FAILED_TO_CREATE_USER",
    FAILED_TO_UPDATE_USER: "FAILED_TO_UPDATE_USER",
}

export const commonErrors = {
    DATABASE_UNAVAILABLE: "DATABASE_UNAVAILABLE",
}